# Install this file as a drop-in under the .network files that manage your uplinks.
# Examples:
#   /etc/systemd/network/20-wireless.network.d/xray-policy.conf
#   /etc/systemd/network/10-wired.network.d/xray-policy.conf

[RoutingPolicyRule]
Family=ipv4
FirewallMark=1
Table=110
Priority=32765

[RoutingPolicyRule]
Family=ipv6
FirewallMark=1
Table=110
Priority=32765
